sudo: required
language: node_js
node_js: lts/*
services:
 - docker

before_install:
 - docker build -t gharaszti/lechat-client ./client
 - docker build -t gharaszti/lechat-api ./api
 - docker build -t gharaszti/lechat-client ./nginx
#Login into docker hub
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push those images to repositories
 - docker push gharaszti/lechat-client
 - docker push gharaszti/lechat-api
 - docker push gharaszti/lechat-nginx